CREATE TABLE `MyWeb`.`TableName1`(
   `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT UNIQUE ,
   `username` VARCHAR(20) DEFAULT 'Null' ,
   `email` VARCHAR(50) NOT NULL ,
   `password` VARCHAR(50) NOT NULL ,
   PRIMARY KEY (`id`, `email`)
 )  ENGINE=INNODB COMMENT='' ROW_FORMAT=DEFAULT CHARSET=utf8